customhost = "database-1.cvxatcorqdgv.us-east-1.rds.amazonaws.com"
customuser = "awsuser1"
custompass = "Bait3273"
customdb = "employee"
custombucket = "wongjunyuen-employee"
customregion = "us-east-1"
